.TH RAVEND 1 "September 2025" "Raven Core" "User Commands"
.SH NAME
ravend \- Raven Core daemon
.SH SYNOPSIS
.B ravend
.RI [ options ]
.SH DESCRIPTION
.B ravend
is the Raven Core daemon. It maintains the Raven blockchain, validates
transactions and blocks, and serves JSON-RPC and P2P network requests.
The daemon can run in the background and be controlled by
.BR raven-cli (1).
.PP
For the complete list of options, run:
.B ravend -help
.SH OPTIONS
.TP
.BR -conf= file
Specify configuration file (default:
.IR raven.conf ).
.TP
.BR -datadir= dir
Specify data directory.
.TP
.B -daemon
Run in the background as a daemon.
.TP
.B -server
Accept JSON-RPC commands.
.TP
.B -printtoconsole
Send log output to the console.
.SH FILES
.TP
.I raven.conf
Configuration file used by Raven Core.
.SH SEE ALSO
.BR raven-cli (1),
.BR raven-qt (1),
.BR raven-tx (1)
.SH COPYRIGHT
Copyright (c) 2009-2025 The Bitcoin Core developers
Copyright (c) 2016-2025 The Raven Core developers
