.TH RAVEN-CLI 1 "September 2025" "Raven Core" "User Commands"
.SH NAME
raven-cli \- Raven Core RPC command line client
.SH SYNOPSIS
.B raven-cli
.RI [ options ] " command " [ params ]
.br
.B raven-cli
.RI [ options ] " help " [ command ]
.br
.B raven-cli
.RI [ options ] " -named " command " name=value " ...
.SH DESCRIPTION
.B raven-cli
sends RPC commands to a running
.BR ravend (1)
or
.BR raven-qt (1)
instance.
.PP
For the complete list of options, run:
.B raven-cli -help
.SH OPTIONS
.TP
.BR -conf= file
Specify configuration file (default:
.IR raven.conf ).
.TP
.BR -datadir= dir
Specify data directory.
.TP
.BR -rpcconnect= ip
Send commands to node running on
.IR ip
(default: 127.0.0.1).
.TP
.BR -rpcport= port
Connect to JSON-RPC on
.IR port .
.TP
.BR -rpcuser= user
RPC username.
.TP
.BR -rpcpassword= password
RPC password.
.TP
.B -named
Pass named arguments to the RPC command.
.SH EXAMPLES
.TP
Get block count:
.B raven-cli getblockcount
.TP
Get blockchain info with named arguments:
.B raven-cli -named getblockchaininfo
.SH SEE ALSO
.BR ravend (1),
.BR raven-qt (1)
.SH COPYRIGHT
Copyright (c) 2009-2025 The Bitcoin Core developers
Copyright (c) 2016-2025 The Raven Core developers
