.TH RAVEN-QT 1 "September 2025" "Raven Core" "User Commands"
.SH NAME
raven-qt \- Raven Core GUI
.SH SYNOPSIS
.B raven-qt
.RI [ options ]
.SH DESCRIPTION
.B raven-qt
is the graphical user interface for Raven Core. It provides a wallet,
network status, and transaction management UI. Most core options are shared
with
.BR ravend (1)
(e.g. data directory, configuration file, and networking options).
.PP
For the complete list of options, run:
.B raven-qt -help
.SH OPTIONS
.TP
.BR -conf= file
Specify configuration file (default:
.IR raven.conf ).
.TP
.BR -datadir= dir
Specify data directory.
.TP
.B -server
Accept JSON-RPC commands.
.TP
.B -min
Start minimized.
.SH SEE ALSO
.BR ravend (1),
.BR raven-cli (1)
.SH COPYRIGHT
Copyright (c) 2009-2025 The Bitcoin Core developers
Copyright (c) 2016-2025 The Raven Core developers
